repos:
  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        language: system
        entry: bash -c "PYTHONPATH=$(pwd)/drf_pyjwt:$PYTHONPATH pipenv run mypy drf_pyjwt"
        pass_filenames: false
        verbose: true
        types: [ "python" ]
